### ISSUE TITLE
Green party emblem not working on leaflet pagews

### ISSUE THREAD

**Issue by goatchurchprime** [electionleaflets/electionleaflets#32] opened 2015-04-28 06:55 UTC
eg https://electionleaflets.org/leaflets/11217/

The image links to a non-existent file:
http://openelectoralcommission.org.uk/party_images/Emblem_1119.jpg

On the other hand, libdems get this:
http://openelectoralcommission.org.uk/party_images/Emblem_106.gif

**Comment by andylolz** [comment] 2015-04-28 07:35
This is a duplicate of DemocracyClub/electionleaflets#62

**Comment by symroe** [comment] 2015-04-30 11:11
This issue was moved to DemocracyClub/electionleaflets#66

**Closed by symroe** 2015-04-30 11:11 UTC
